# Build Angular Universal App
FROM node:12-alpine

LABEL maintainer="Yasmany Santalla Pereda <ysantalla88@gmail.com>"

WORKDIR /opt/client

COPY . ./
#RUN npm install

ENV PATH="./node_modules/.bin:$PATH"

RUN npm run build:ssr

EXPOSE 4000

CMD ["npm", "run", "serve:ssr"]
